### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by sonicviz** [DeligenceTechnologies/PanoplyCMS#4]
With message below.
Also, should the instructions for method 2 say to do "npm install" before "meteor"?

G:\Meteor Projects\Project X\Panoplycms-master>meteor
[[[[[ ~\G\Meteor Projects\Project X\Panoplycms-master ]]]]]

=> Started proxy.
=> Meteor 1.4.1.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Errors prevented startup:

   While loading package npm-bcrypt@0.8.7_1:
   error: Command failed: gyp
   npm ERR! Windows_NT 10.0.14393
   npm ERR! argv "C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\bin\\node.exe"
   "C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\bin\npm-cli.js" "rebuild"
   npm ERR! node v0.10.45
   npm ERR! npm  v3.9.6
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   gyp
   npm ERR! Windows_NT 10.0.14393
   npm ERR! argv "C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\bin\\node.exe"
   "C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\bin\npm-cli.js" "rebuild"
   npm ERR! node v0.10.45
   npm ERR! npm  v3.9.6
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

=> Your application has errors. Waiting for file change.

**Comment by deligence** [comment]
Please check it now and do let me know in case you still face any issue. We have recently updated our code.
