### ISSUE TITLE
Error on install (Mac OS Sierra)

### ISSUE THREAD

**Issue by aj-jhaveri** [DeligenceTechnologies/PanoplyCMS#5]
Hi, I am receiving the following error: 

deligencetechnologies:panoplycms-core/admin/common/alertMessage.jsx:39: Only one default export allowed per module. (39:0)
   
=> Your application has errors. Waiting for file change.

Any ideas?

**Comment by deligence** [comment]
Hi @aj-jhaveri 
Above issue has been resolved. Please check.
Thanks.

**Comment by deligence** [comment]
Did you get a chance to check it?
