### ISSUE TITLE
Update your .gitignore

### ISSUE THREAD

**Issue by thekavish** [DeligenceTechnologies/PanoplyCMS#6]
Track your package.json file but add `/node_modules` to your .gitignore file. @saransh1525

**Comment by ghost** [comment]
Hi Kavish,

Please check now.

Regards,
Saransh

**Comment by thekavish** [comment]
`/.meteor` and `/node_modules` still shows in your repository's master branch. I guess it should not show.

**Comment by thekavish** [comment]
This answer might come in handy for untracking `/.meteor` folder.
[How to make Git “forget” about a file that was tracked but is now in .gitignore?](https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore#answer-19095988)
